Repository YAPP-19th/Android-Team-2-Backend, pull requests merged in 2021-11, with the labels that each got.

#42 Feature/#25 logback
  document/logback.md
  module-api/src/main/java/com/yapp/sharefood/flavor/controller/FlavorController.java
  module-api/src/main/java/com/yapp/sharefood/user/controller/UserFlavorController.java
  module-api/src/main/resources/logback-spring.xml
Labels: task

#47 Feature/#44 userflavor controller test
  module-api/src/main/java/com/yapp/sharefood/flavor/advice/FlavorAdviceController.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserFlavorControllerTest.java
Labels: task

#50 Hotfix/#45 foodrank issue
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodCategoryController.java
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodController.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
  module-domain/src/main/java/com/yapp/sharefood/category/domain/Category.java
  module-domain/src/main/java/com/yapp/sharefood/category/domain/ChildCategories.java
  module-domain/src/main/java/com/yapp/sharefood/like/repository/custom/LikeCustomRepository.java
  module-domain/src/main/java/com/yapp/sharefood/like/repository/custom/LikeCustomRepositoryImpl.java
Labels: bug

#52 Hotfix/#45 foodrank issue
  module-domain/src/test/java/com/yapp/sharefood/category/domain/CategoryTest.java
Labels: bug

#51 Dev
  module-api/src/main/java/com/yapp/sharefood/flavor/advice/FlavorAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodCategoryController.java
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodController.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserFlavorControllerTest.java
  module-domain/src/main/java/com/yapp/sharefood/category/domain/Category.java
  module-domain/src/main/java/com/yapp/sharefood/category/domain/ChildCategories.java
  module-domain/src/main/java/com/yapp/sharefood/like/repository/custom/LikeCustomRepository.java
  module-domain/src/main/java/com/yapp/sharefood/like/repository/custom/LikeCustomRepositoryImpl.java
  module-domain/src/test/java/com/yapp/sharefood/category/domain/CategoryTest.java
Labels: bug, task

#53 Feature/#48 savefood
  module-api/src/main/java/com/yapp/sharefood/common/advice/CommonAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/flavor/service/FlavorService.java
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodController.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/main/java/com/yapp/sharefood/tag/service/TagService.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/like/service/LikeServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/tag/service/TagServiceTest.java
  module-common/src/main/java/com/yapp/sharefood/common/exception/BadRequestException.java
  module-common/src/main/java/com/yapp/sharefood/common/exception/file/FileTypeValidationException.java
Labels: task

#54 Feature/#49 user api docs
  document/api-docs.md
  module-api/build.gradle
  module-api/src/docs/asciidoc/user/me-get.adoc
  module-api/src/docs/asciidoc/user/nickname-get.adoc
  module-api/src/docs/asciidoc/user/nickname-patch.adoc
  module-api/src/docs/asciidoc/user/nickname-validation-get.adoc
  module-api/src/docs/asciidoc/user/other-get.adoc
  module-api/src/test/java/com/yapp/sharefood/common/PreprocessController.java
  module-api/src/test/java/com/yapp/sharefood/common/documentation/DocumentRequestBuilder.java
  module-api/src/test/java/com/yapp/sharefood/common/documentation/DocumentationUtils.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserControllerTest.java
Labels: task

#58 Feature/#57 foodsearch
  module-api/src/main/java/com/yapp/sharefood/category/advice/CategoryAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/food/advice/FoodAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodCategoryController.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/request/FoodPageSearchRequest.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/response/FoodPageResponse.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/main/java/com/yapp/sharefood/like/controller/LikeController.java
  module-api/src/main/java/com/yapp/sharefood/like/dto/request/LikeCreationRequest.java
  module-api/src/main/java/com/yapp/sharefood/like/dto/request/LikeDeleteRequest.java
  module-common/src/main/java/com/yapp/sharefood/common/exception/ParameterException.java
  module-domain/src/main/java/com/yapp/sharefood/common/order/SortType.java
  module-domain/src/main/java/com/yapp/sharefood/food/dto/FoodOrderType.java
  module-domain/src/main/java/com/yapp/sharefood/food/dto/FoodPageSearch.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/FoodQueryRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/FoodQueryRepositoryImpl.java
  module-domain/src/main/java/com/yapp/sharefood/like/repository/custom/LikeCustomRepositoryImpl.java
  module-domain/src/main/java/com/yapp/sharefood/tag/repository/TagRepository.java
Labels: task

#60 Feature/#55 bookmark
  module-api/src/docs/asciidoc/bookmark/delete.adoc
  module-api/src/docs/asciidoc/bookmark/post.adoc
  module-api/src/main/java/com/yapp/sharefood/bookmark/advice/BookmarkAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/bookmark/controller/BookmarkController.java
  module-api/src/main/java/com/yapp/sharefood/bookmark/service/BookmarkService.java
  module-api/src/test/java/com/yapp/sharefood/bookmark/controller/BookmarkControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/bookmark/service/BookmarkServiceTest.java
  module-common/src/main/java/com/yapp/sharefood/bookmark/exception/BookmarkAlreadyExistException.java
  module-common/src/main/java/com/yapp/sharefood/bookmark/exception/BookmarkNotFoundException.java
  module-common/src/main/java/com/yapp/sharefood/food/exception/FoodNotFoundException.java
  module-domain/src/main/java/com/yapp/sharefood/bookmark/domain/Bookmark.java
  module-domain/src/main/java/com/yapp/sharefood/bookmark/repository/BookmarkRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Bookmarks.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Food.java
Labels: task

#61 fix: multipart file로 인해서 request 형태 변경
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodController.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/request/FoodCreationRequest.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/request/FoodImageCreateRequest.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/response/FoodImageCreateResponse.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodImageService.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/test/java/com/yapp/sharefood/common/StubFileUploader.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodImageServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
Labels: bug

#66 Feature/#64 foodpage
  module-api/src/main/java/com/yapp/sharefood/food/dto/request/FoodPageSearchRequest.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodImageServiceTest.java
  module-common/src/main/java/com/yapp/sharefood/common/utils/QueryUtils.java
  module-domain/src/main/java/com/yapp/sharefood/flavor/domain/FlavorType.java
  module-domain/src/main/java/com/yapp/sharefood/flavor/repository/FlavorRepository.java
  module-domain/src/main/java/com/yapp/sharefood/flavor/repository/query/FlavorQueryRepository.java
  module-domain/src/main/java/com/yapp/sharefood/flavor/repository/query/FlavorQueryRepositoryImpl.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Food.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Likes.java
  module-domain/src/main/java/com/yapp/sharefood/food/dto/FoodPageSearch.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/FoodRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/FoodTagRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepositoryImpl.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodTagQueryRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodTagQueryRepositoryImpl.java
  module-domain/src/main/java/com/yapp/sharefood/like/domain/Like.java
  module-domain/src/main/java/com/yapp/sharefood/userflavor/repository/UserFlavorRepository.java
Labels: enhancement

#69 Feature/#62 rest docs
  document/api-docs.md
  module-api/src/docs/asciidoc/auth/post.adoc
  module-api/src/docs/asciidoc/auth/signup.adoc
  module-api/src/docs/asciidoc/category/get.adoc
  module-api/src/docs/asciidoc/tag/get.adoc
  module-api/src/docs/asciidoc/user-flavor/get.adoc
  module-api/src/docs/asciidoc/user-flavor/post.adoc
  module-api/src/test/java/com/yapp/sharefood/auth/controller/AuthControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/category/controller/CategoryControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/common/DocumentTest.java
  module-api/src/test/java/com/yapp/sharefood/common/PreprocessController.java
  module-api/src/test/java/com/yapp/sharefood/common/documentation/DocumentRequestBuilder.java
  module-api/src/test/java/com/yapp/sharefood/common/documentation/DocumentationUtils.java
  module-api/src/test/java/com/yapp/sharefood/flavor/controller/FlavorControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/tag/controller/TagControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserFlavorControllerTest.java
  module-common/src/main/java/com/yapp/sharefood/common/exception/ForbiddenException.java
  module-common/src/main/java/com/yapp/sharefood/flavor/exception/FlavorNotFoundException.java
  module-common/src/main/java/com/yapp/sharefood/oauth/exception/UserNotFoundException.java
  module-common/src/main/java/com/yapp/sharefood/user/exception/UserNicknameExistException.java
Labels: task
