Repository YAPP-19th/Android-Team-2-Backend, pull requests merged in 2021-12, with the labels that each got.

#81 Feature/#65 foodtestcode
  module-api/src/main/java/com/yapp/sharefood/food/dto/request/FoodPageSearchRequest.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodFindPageTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Food.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/TagWrapper.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/FoodFlavorRepository.java
Labels: enhancement

#82 Feature/#76 user grade
  logs/sharedfood-2021-11-29.log
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodController.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/FoodStatus.java
  module-domain/src/main/java/com/yapp/sharefood/user/domain/Grade.java
  module-domain/src/main/java/com/yapp/sharefood/user/domain/User.java
  module-domain/src/test/java/com/yapp/sharefood/user/domain/GradeTest.java
Labels: task

#85 Dev
  appspec.yml
  logs/sharedfood-2021-11-29.log
  module-api/src/main/java/com/yapp/sharefood/auth/controller/AuthController.java
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodController.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/FoodPageDto.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/request/FoodCreationRequest.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/request/FoodPageSearchRequest.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodImageService.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/main/java/com/yapp/sharefood/like/controller/LikeController.java
  module-api/src/main/resources/application.yml
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodFindPageTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/like/service/LikeServiceTest.java
  module-common/src/main/java/com/yapp/sharefood/common/exception/DbUserLockException.java
  module-domain/src/main/java/com/yapp/sharefood/common/order/SortType.java
  module-domain/src/main/java/com/yapp/sharefood/config/datasource/DatasourceConfig.java
  module-domain/src/main/java/com/yapp/sharefood/config/lock/UserlevelLock.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Food.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/FoodStatus.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/TagWrapper.java
  module-domain/src/main/java/com/yapp/sharefood/food/dto/FoodPageSearch.java
  module-domain/src/main/java/com/yapp/sharefood/food/dto/OrderType.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/FoodFlavorRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepositoryImpl.java
  module-domain/src/main/java/com/yapp/sharefood/user/domain/Grade.java
  module-domain/src/main/java/com/yapp/sharefood/user/domain/User.java
  module-domain/src/main/java/com/yapp/sharefood/userflavor/domain/UserFlavor.java
  module-domain/src/main/resources/application-domain-dev.yml
  module-domain/src/main/resources/application-domain-local.yml
  module-domain/src/test/java/com/yapp/sharefood/user/domain/GradeTest.java
  script/aws-deploy.sh
Labels: enhancement, task

#92 Feature/#86 food controller test
  module-api/src/docs/asciidoc/food/post.adoc
  module-api/src/docs/asciidoc/like/delete.adoc
  module-api/src/docs/asciidoc/like/post.adoc
  module-api/src/main/java/com/yapp/sharefood/common/advice/CommonAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/request/FoodImageCreateRequest.java
  module-api/src/main/java/com/yapp/sharefood/like/controller/LikeController.java
  module-api/src/main/java/com/yapp/sharefood/like/dto/request/LikeDeleteRequest.java
  module-api/src/test/java/com/yapp/sharefood/bookmark/controller/BookmarkControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/category/controller/CategoryControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/like/controller/LikeControllerTest.java
  module-domain/src/main/java/com/yapp/sharefood/config/datasource/DatasourceConfig.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepositoryImpl.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodTagQueryRepositoryImpl.java
Labels: enhancement, task

#94 Feature/#86 food controller test
  .gitignore
  logs/sharedfood-2021-11-29.log
  module-api/src/docs/asciidoc/food/get.adoc
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodCategoryController.java
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodController.java
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodSaveController.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/response/FoodDetailResponse.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/main/java/com/yapp/sharefood/local/MockData.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodSaveControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
  module-common/src/main/java/com/yapp/sharefood/common/exception/BadRequestException.java
  module-common/src/main/java/com/yapp/sharefood/common/random/RandomStringCreator.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Bookmarks.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Food.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Likes.java
Labels: enhancement

#96 Feature/#86 food controller test
  module-api/src/docs/asciidoc/food/delete.adoc
  module-api/src/docs/asciidoc/food/get.adoc
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodController.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/FoodPageDto.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/response/FoodPageResponse.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodFindPageTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
Labels: enhancement

#101 refactor: flavor request 형식 수정
  module-api/src/main/java/com/yapp/sharefood/flavor/dto/request/UserFlavorRequest.java
  module-api/src/main/java/com/yapp/sharefood/flavor/dto/response/UpdateUserFlavorResponse.java
  module-api/src/main/java/com/yapp/sharefood/flavor/service/FlavorService.java
  module-api/src/main/java/com/yapp/sharefood/food/dto/request/FoodCreationRequest.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/main/java/com/yapp/sharefood/user/controller/UserFlavorController.java
  module-api/src/test/java/com/yapp/sharefood/flavor/service/FlavorServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodSaveControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserFlavorControllerTest.java
  module-domain/src/main/java/com/yapp/sharefood/user/domain/User.java
Labels: duplicate, enhancement

#106 Feature/#105 logback
  module-api/src/main/java/com/yapp/sharefood/auth/advice/AuthAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/bookmark/advice/BookmarkAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/category/advice/CategoryAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/common/advice/CommonAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/favorite/advice/FavoriteAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/flavor/advice/FlavorAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/food/advice/FoodAdviceController.java
  module-api/src/main/resources/console-appender.xml
  module-api/src/main/resources/file-error-appender.xml
  module-api/src/main/resources/file-error-aws-appender.xml
  module-api/src/main/resources/file-info-appender.xml
  module-api/src/main/resources/file-info-aws-appender.xml
  module-api/src/main/resources/file-warn-appender.xml
  module-api/src/main/resources/file-warn-aws-appender.xml
  module-api/src/main/resources/logback-spring.xml
  module-domain/src/main/java/com/yapp/sharefood/config/lock/UserlevelLock.java
  module-external/src/main/java/com/yapp/sharefood/external/s3/AwsS3Uploader.java
Labels: enhancement

#115 fix: UserFlavor 로직 오류 수정
  module-api/src/main/java/com/yapp/sharefood/flavor/service/FlavorService.java
  module-api/src/main/java/com/yapp/sharefood/user/controller/UserFlavorController.java
  module-api/src/test/java/com/yapp/sharefood/flavor/service/FlavorServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserFlavorControllerTest.java
  module-domain/src/main/java/com/yapp/sharefood/user/domain/User.java
  module-domain/src/main/java/com/yapp/sharefood/user/domain/UserFlavors.java
Labels: bug

#117 Feature/#74 favorite find
  module-api/src/main/java/com/yapp/sharefood/favorite/advice/FavoriteAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/favorite/controller/FavoriteController.java
  module-api/src/main/java/com/yapp/sharefood/favorite/dto/FavoriteFoodDto.java
  module-api/src/main/java/com/yapp/sharefood/favorite/dto/response/FavoriteFoodResponse.java
  module-api/src/main/java/com/yapp/sharefood/favorite/service/FavoriteService.java
  module-api/src/test/java/com/yapp/sharefood/favorite/controller/FavoriteControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/favorite/service/FavoriteServiceTest.java
  module-common/src/main/java/com/yapp/sharefood/favorite/exception/TooManyFavoriteException.java
  module-domain/src/main/java/com/yapp/sharefood/favorite/repository/FavoriteRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Food.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepositoryImpl.java
Labels: task

#129 Hotfix/#127 omitted data
  module-api/src/docs/asciidoc/food-me/get/success/success.adoc
  module-api/src/docs/asciidoc/food/post/success/success.adoc
  module-api/src/main/java/com/yapp/sharefood/favorite/controller/FavoriteController.java
  module-api/src/main/java/com/yapp/sharefood/favorite/dto/request/FavoriteCreationRequest.java
  module-api/src/main/java/com/yapp/sharefood/favorite/service/FavoriteService.java
  module-api/src/test/java/com/yapp/sharefood/favorite/controller/FavoriteControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/favorite/service/FavoriteServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodSaveControllerTest.java
  module-domain/src/main/java/com/yapp/sharefood/bookmark/domain/Bookmark.java
  module-domain/src/main/java/com/yapp/sharefood/favorite/domain/Favorite.java
  module-domain/src/main/java/com/yapp/sharefood/favorite/query/FavoriteQueryRepository.java
  module-domain/src/main/java/com/yapp/sharefood/favorite/query/FavoriteQueryRepositoryImpl.java
  module-domain/src/main/java/com/yapp/sharefood/favorite/repository/FavoriteRepository.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Favorites.java
  module-domain/src/main/java/com/yapp/sharefood/like/domain/Like.java
Labels: bug, enhancement

#132 Feature/#121 aop
  module-api/build.gradle
  module-api/src/main/java/com/yapp/sharefood/aop/RepositoryLoggingAspect.java
  module-api/src/main/java/com/yapp/sharefood/healthcheck/controller/HealthCheckController.java
Labels: enhancement
