Repository YAPP-19th/Android-Team-2-Backend, pull requests merged in 2022-01, with the labels that each got.

#134 Feature/#133
  module-api/src/main/java/com/yapp/sharefood/favorite/dto/FavoriteFoodDto.java
  module-api/src/main/java/com/yapp/sharefood/user/dto/UserInfoDto.java
  module-api/src/test/java/com/yapp/sharefood/favorite/controller/FavoriteControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserControllerTest.java
Labels: task

#139 Hotfix/#138
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepositoryImpl.java
Labels: bug

#141 Feature/#131 index
  module-domain/src/main/resources/db/migration/V2__food_tag_index.sql
  module-domain/src/main/resources/db/migration/V3__food_searching_index.sql
Labels: enhancement

#142 Dev
  module-api/src/docs/.DS_Store
  module-api/src/docs/asciidoc/food-bookmark/get/success/success.adoc
  module-api/src/docs/asciidoc/food-me/get/success/success.adoc
  module-api/src/docs/asciidoc/food-rank/fail/badRequest-datePeriod.adoc
  module-api/src/docs/asciidoc/food-rank/fail/badRequest-top.adoc
  module-api/src/docs/asciidoc/food-recommendation/fail/badRequest-datePeriod.adoc
  module-api/src/docs/asciidoc/food-recommendation/fail/badRequest-top.adoc
  module-api/src/docs/asciidoc/user-me/get/success/success.adoc
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserControllerTest.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepositoryImpl.java
  module-domain/src/main/resources/db/migration/V2__food_tag_index.sql
  module-domain/src/main/resources/db/migration/V3__food_searching_index.sql
Labels: bug, enhancement

#146 Feature/#145 flywaydata
  module-domain/src/main/resources/db/migration/V4__category_data.sql
  module-domain/src/main/resources/db/migration/V5__flavor_data.sql
Labels: enhancement

#147 Feature/#143 withdrawal user
  module-api/src/docs/asciidoc/user-me/delete/fail/userNotFound.adoc
  module-api/src/docs/asciidoc/user-me/delete/success/success.adoc
  module-api/src/main/java/com/yapp/sharefood/user/controller/UserController.java
  module-api/src/main/java/com/yapp/sharefood/user/service/UserService.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/user/service/UserServiceTest.java
Labels: task

#149 fix: flavor 정보를 찾지 못할 경우 정보 검색 실패로 로직 수정
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepositoryImpl.java
Labels: bug

#150 Feature/#148 food detail response
  module-api/src/docs/asciidoc/food-me/get/success/success.adoc
  module-api/src/main/java/com/yapp/sharefood/food/dto/response/FoodDetailResponse.java
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodSaveControllerTest.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Food.java
Labels: task

#156 hotfix: food dto에서 최애 정보 좋아요 정보 북마크 정보 가져오는 로직 누락
  module-api/src/main/java/com/yapp/sharefood/food/dto/FoodPageDto.java
  module-domain/src/main/java/com/yapp/sharefood/bookmark/domain/Bookmark.java
  module-domain/src/main/java/com/yapp/sharefood/favorite/domain/Favorite.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Bookmarks.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Favorites.java
  module-domain/src/main/java/com/yapp/sharefood/food/domain/Likes.java
  module-domain/src/main/java/com/yapp/sharefood/like/domain/Like.java
Labels: bug

#157 Hotfix/#155
  module-api/src/main/java/com/yapp/sharefood/food/service/FoodService.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodFindPageTest.java
  module-domain/src/main/java/com/yapp/sharefood/food/dto/FoodMinePageSearch.java
  module-domain/src/main/java/com/yapp/sharefood/food/repository/query/FoodQueryRepositoryImpl.java
  script/real-deploy.sh
Labels: bug

#160 hotfix: writer가 회원탈퇴할 경우 조회 이슈 발생 이슈 해결
  module-domain/src/main/java/com/yapp/sharefood/food/repository/FoodRepository.java
Labels: bug

#161 Feature/#116 facade
  module-api/src/main/java/com/yapp/sharefood/food/controller/FoodSaveController.java
  module-api/src/main/java/com/yapp/sharefood/food/facade/FoodSaveFacade.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodSaveControllerTest.java
  script/real-deploy.sh
Labels: enhancement, refactor

#165 Feature/#164 refresh token
  module-api/src/main/java/com/yapp/sharefood/auth/controller/AuthController.java
  module-api/src/main/java/com/yapp/sharefood/auth/service/AuthService.java
  module-api/src/test/java/com/yapp/sharefood/auth/controller/AuthControllerTest.java
Labels: enhancement, task

#170 Feature/#159 refactor
  module-api/src/test/java/com/yapp/sharefood/SharefoodApplicationTests.java
  module-api/src/test/java/com/yapp/sharefood/auth/controller/AuthControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/auth/manager/AuthenticationManagerTest.java
  module-api/src/test/java/com/yapp/sharefood/auth/service/AuthServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/bookmark/controller/BookmarkControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/bookmark/service/BookmarkServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/category/controller/CategoryControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/category/service/CategoryServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/common/DocumentTest.java
  module-api/src/test/java/com/yapp/sharefood/common/PreprocessController.java
  module-api/src/test/java/com/yapp/sharefood/common/controller/PreprocessController.java
  module-api/src/test/java/com/yapp/sharefood/common/controller/documentation/DocumentationUtils.java
  module-api/src/test/java/com/yapp/sharefood/common/service/IntegrationService.java
  module-api/src/test/java/com/yapp/sharefood/favorite/controller/FavoriteControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/favorite/service/FavoriteServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/flavor/controller/FlavorControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/flavor/service/FlavorServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodReportControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodSaveControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodFindPageTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodImageServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodReportServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/food/service/FoodServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/like/controller/LikeControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/like/service/LikeServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/tag/controller/TagControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/tag/service/TagServiceTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserFlavorControllerProcess.java
  module-api/src/test/java/com/yapp/sharefood/user/service/UserServiceTest.java
  module-common/src/main/java/com/yapp/sharefood/common/utils/ValidPortUtils.java
  module-external/src/main/java/com/yapp/sharefood/config/aws/LocalEmbeddedS3Config.java
Labels: enhancement

#173 Feature/#172 error refactor
  module-api/src/docs/asciidoc/food/post/fail/badRequest.adoc
  module-api/src/docs/asciidoc/food/post/fail/categoryNotFound.adoc
  module-api/src/docs/asciidoc/food/post/fail/invalidOperation.adoc
  module-api/src/main/java/com/yapp/sharefood/auth/advice/AuthAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/auth/service/AuthService.java
  module-api/src/main/java/com/yapp/sharefood/bookmark/advice/BookmarkAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/common/advice/CommonAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/common/error/ErrorResponse.java
  module-api/src/main/java/com/yapp/sharefood/favorite/advice/FavoriteAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/flavor/advice/FlavorAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/food/advice/FoodAdviceController.java
  module-api/src/main/java/com/yapp/sharefood/user/advice/UserAdviceController.java
  module-api/src/test/java/com/yapp/sharefood/auth/controller/AuthControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/bookmark/controller/BookmarkControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/favorite/controller/FavoriteControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodReportControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/food/controller/FoodSaveControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/like/controller/LikeControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserControllerTest.java
  module-api/src/test/java/com/yapp/sharefood/user/controller/UserFlavorControllerProcess.java
  module-common/src/main/java/com/yapp/sharefood/bookmark/exception/BookmarkAlreadyExistException.java
  module-common/src/main/java/com/yapp/sharefood/bookmark/exception/BookmarkNotFoundException.java
  module-common/src/main/java/com/yapp/sharefood/common/exception/BadRequestException.java
  module-common/src/main/java/com/yapp/sharefood/common/exception/ForbiddenException.java
  module-common/src/main/java/com/yapp/sharefood/favorite/exception/AlreadyFavoriteExistException.java
  module-common/src/main/java/com/yapp/sharefood/favorite/exception/FavoriteNotFoundException.java
  module-common/src/main/java/com/yapp/sharefood/favorite/exception/TooManyFavoriteException.java
  module-common/src/main/java/com/yapp/sharefood/flavor/exception/FlavorNotFoundException.java
  module-common/src/main/java/com/yapp/sharefood/food/exception/FoodBanndedException.java
  module-common/src/main/java/com/yapp/sharefood/food/exception/FoodNotFoundException.java
  module-common/src/main/java/com/yapp/sharefood/oauth/exception/OAuthTypeNotFoundException.java
  module-common/src/main/java/com/yapp/sharefood/oauth/exception/UserNotFoundException.java
  module-common/src/main/java/com/yapp/sharefood/report/exception/ReportNotDefineException.java
  module-common/src/main/java/com/yapp/sharefood/user/exception/UserBanndedException.java
  module-common/src/main/java/com/yapp/sharefood/user/exception/UserNicknameExistException.java
Labels: refactor
